### ISSUE TITLE
Adding paths.base makes index.html disappear from build

### ISSUE THREAD

**Issue by psmpm** [metonym/sveltekit-gh-pages#2]
I've been following the steps in the README, but when I get to adding paths.base all of a sudden, after I add it, index.html is no longer generated. Why is this?

**Comment by metonym** [comment]
Thanks for reporting. I'm able to repro the same issue when using SvelteKit v1.0.0-next.328 or above, which appears to be a regression.

In the meantime, can you try using SvelteKit v1.0.0-next.327?

**Comment by metonym** [comment]
Looks like it may be this issue (https://github.com/sveltejs/kit/issues/4927) with a [pending fix](https://github.com/sveltejs/kit/pull/4928).

**Comment by psmpm** [comment]
Alright, apparently it was merged about half an hour ago, and is pending release. I'll try v1.0.0-next.327 for now, and I'll update to the latest version when the fix is released. Thanks!

**Comment by metonym** [comment]
Commenting for posterity.

It appears this is now fixed in SvelteKit version [1.0.0-next.331](https://github.com/sveltejs/kit/blob/79ac9d450b3c6a9187300d576db856bbced854af/packages/kit/CHANGELOG.md#100-next331).
