### ISSUE TITLE
npm run deploy doesn't change img path

### ISSUE THREAD

**Issue by rvcristiand** [metonym/sveltekit-gh-pages#3]
Hi.

I have made a simple app using your repository. I tried to put a image in a img element. In my code I have something like this
````
<script>
	import logo from '$lib/images/logo.png';
</script>

<header>
	<div class="corner">
		<a href="https://www.mypersonalweb.gov.co/">
			<img src="{logo}" alt="My personal web" />
		</a>
	</div>
</header>
````

But when I go to check the img src after `npm run deploy` i got:
````
<img src="/sveltekit-gh-pages/_app/immutable/assets/defensoria-pueblo.1dc2ac36.png" alt="Defensoría del Pueblo de Colombia" class="svelte-1st7820">
````

I tried to change svelte.config.js to:
```
import adapter from "@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
    paths: {
      base: "/formulario-app",
    },
  },
};

export default config;
```

But doesn't work.

Any ideas ?

**Comment by rvcristiand** [comment]
I realized my error. I don't create the .nojekyll file. I have some problems with touch

**Comment by rvcristiand** [comment]
I had bad moment using this repo in windows. I couldn't automate create `.nojekyll` file. I resolved using `type nul>build/.nojekyll`

**Comment by mskocik** [comment]
When you create `.nojekyll` file in `root/static` folder, it will be copied into build directory.

**Comment by metonym** [comment]
I've amended the repo to follow @mskocik's approach, which is also recommended by the official SvelteKit docs.

An empty `.nojekyll` file (0838b0e) has been added to the `static` folder, which should eliminate cross-OS issues altogether.
